=== paulegan/old-code/dig/hitbox/hitbox_map.dtd
<?xml encoding="ISO-8859-1"?>
<!-- $Id: hitbox_map.dtd,v 1.1 2001/11/06 23:35:23 pegan Exp $ -->
<!ELEMENT hitbox_map (unit+) >
<!ELEMENT unit (map+) >
<!ATTLIST unit country_code CDATA #REQUIRED
               unit_code CDATA #REQUIRED
               brand_code CDATA #REQUIRED >
<!ELEMENT map (account,category) >
<!ELEMENT account (#PCDATA) >
<!ELEMENT category (#PCDATA) >

=== paulegan/old-code/dig/src/perl/WDIG/HitBox/t/hitbox_map.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE hitbox_map PUBLIC "-//Disney Enterprises, Inc.//DTD HitBox Account Map 1.1//EN" "http://hitbox.disneyinternational.com/hitbox_map.dtd">
 
<hitbox_map>
 
 <unit country_code="IE" unit_code="NONE" brand_code="DIS">
  <map><account>DM888888XXXX38EN3</account><category>/</category></map>
  <map><account>DM000000XXXX38EN3</account><category>/IE</category></map>
  <map><account>DM444444XXXX38EN3</account><category>/EMEA/IE</category></map>
 </unit>
 
 <unit country_code="IE" unit_code="BVI" brand_code="DIS">
  <map><account>DM888888XXXX38EN3</account><category>/BVI</category></map>
  <map><account>DM000000XXXX38EN3</account><category>/IE/BVI</category></map>
  <map><account>DM444444XXXX38EN3</account><category>/EMEA/IE/BVI</category></map>
 </unit>
 
 <unit country_code="IE" unit_code="NONE" brand_code="LUMPY">
  <map><account>DM333333XXXX38EN3</account><category>/</category></map>
  <map><account>DM888888XXXX38EN3</account><category>/LUMPY</category></map>
  <map><account>DM000000XXXX38EN3</account><category>/IE/LUMPY</category></map>
  <map><account>DM444444XXXX38EN3</account><category>/EMEA/IE/LUMPY</category></map>
 </unit>

</hitbox_map>
