=== paulegan/old-code/dig/hitbox/url_map.dtd
<?xml encoding="ISO-8859-1"?>
<!-- $Id: url_map.dtd,v 1.1 2001/11/08 20:09:43 pegan Exp $ -->
<!ELEMENT url_map (site+) >
<!ELEMENT site (path+) >
<!ATTLIST site host CDATA #IMPLIED
               root CDATA #IMPLIED >
<!ELEMENT path ((country,unit,brand,site_name?)?) >
<!ATTLIST path pattern CDATA #REQUIRED
               order CDATA #REQUIRED >
<!ELEMENT country (#PCDATA) >
<!ELEMENT unit (#PCDATA) >
<!ELEMENT brand (#PCDATA) >
<!ELEMENT site_name (#PCDATA) >

=== paulegan/old-code/dig/src/perl/WDIG/HitBox/t/url_map.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE url_map PUBLIC "-//Disney Enterprises, Inc.//DTD HitBox URL Map 1.1//EN" "http://hitbox.disneyinternational.com/url_map.dtd">
 
<url_map>
 
 <site host="disney.ie" root="/docs">
  <path pattern="/films/*" order="1">
   <country>IE</country>
   <unit>BVI</unit>
   <brand>DIS</brand>
  </path>
  <path pattern="*/lumpy/*" order="9">
   <country>IE</country>
   <unit>NONE</unit>
   <brand>LUMPY</brand>
  </path>
  <path pattern="*" order="0">
   <country>IE</country>
   <unit>NONE</unit>
   <brand>DIS</brand>
  </path>
 </site>
  
 <site host="pingu" root="/pingu">
  <path pattern="*" order="0">
   <country>INTL</country>
   <unit>NONE</unit>
   <brand>DIS</brand>
  </path>
 </site>

</url_map>
